- hosts: all
  become: true
  any_errors_fatal: true
  become_method: sudo
  roles:
    - 'docker'
  pre_tasks:
    - name: apt update
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
