- hosts: all
  become: true
  any_errors_fatal: true
  become_method: sudo
  roles:
    - role: docker
      tags: [ docker ]
    - role: application_container
      tags: [ application ]
    - role: nginx
      tags: [ nginx ]
  pre_tasks:
    - name: apt update
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install python pip
      apt: name=python3-pip state=latest update_cache=yes
    - name: install Docker SDK for Python
      pip:
        name:
          - docker
  post_tasks:
    - name: Print the URL for the websites
      ansible.builtin.debug:
        msg:
        - "Your static http website url is http://'{{ hostvars[inventory_hostname]['ansible_env'].SSH_CONNECTION.split(' ')[2] }}':8090"
        - "Your static https website url is https://'{{ hostvars[inventory_hostname]['ansible_env'].SSH_CONNECTION.split(' ')[2] }}':443"
